### ISSUE TITLE
setup@v3 fails with `Cannot find module 'semver'`

### ISSUE THREAD

**Issue by aybabtme** [pkgxdev/setup#260]
Hi, it's nice to see a lot of work landing on pkgx, I love this project. With the release of v2 yesterday, I'm fixing my scripts and CI pipeline. It looks like the `pkgxdev/setup@v3` is missing something, it doesn't appear to work with the simple workflow described below:

```yaml
name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: pkgxdev/setup@v3
```

I get the following error.
```
Run pkgxdev/setup@v3
  with:
    version: ^2
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'semver'
Require stack:
- /home/runner/work/_actions/pkgxdev/setup/v3/action.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/runner/work/_actions/pkgxdev/setup/v3/action.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/_actions/pkgxdev/setup/v3/action.js' ]
}

Node.js v20.18.0
```

Thanks for your work on this project! <3
